### PR TITLE
Add Gamepad QT demo, and .gitignore

### PR DESCRIPTION
**Pull request by kattni**

### CODE REVIEW

**Comment by caternuson** [comment]
Why the .gitignore?

**Comment by kattni** [comment]
Because MacOS is a jerk and adds that file to every directory, and `.gitignore` was quicker than deleting the file. I can remove it if you would prefer.

**Comment by caternuson** [comment]
Yes please, just to keep this PR clean. Can open a separate issue pointing out there's no .gitignore and that way can add one for this and maybe other things.

**Comment by kattni** [comment]
Done.

**Comment by caternuson** [comment]
LGTM based on looking at schematic and checking pins. Did not test (don't have HW).

**Review by caternuson — APPROVED** [review]

**Pull request merged**
