### PR TITLE
Fixed typo preventing motor powers below 100%

### PR DESCRIPTION
**Pull request by codydg**
fabs inputs and outputs doubles (as opposed to abs which uses integers, and fabsf which uses floats). abs(value) takes all values below 100% power and rounds them down to 0% power.

### CODE REVIEW

**Comment by ladyada** [comment]
just verified on a circuit Playground express setting throttle to 0.5 does the right thing

**Comment by codydg** [comment]
I have the [Feather HUZZAH w/ ESP8266](https://www.adafruit.com/product/3213) on a [Crickit](https://www.adafruit.com/product/3343), and I'm compiling using [PlatformIO in Visual Studio Code](https://platformio.org/platformio-ide). 

I've attached an example file which, when I run it, only drives the motor when throttle is +- 1.0, but if I change abs to fabs, it works as intended.

[main.zip](https://github.com/adafruit/Adafruit_Seesaw/files/2611769/main.zip)

**Comment by ladyada** [comment]
ahh this is probably an espressif thing

**Comment by ladyada** [comment]
thanks!

**Pull request merged**
