### PR TITLE
Increase touchRead delay for soil sensor

### PR DESCRIPTION
**Pull request by mihai-dinculescu**
The new soil sensor firmware requires a larger delay.

### CODE REVIEW

**Comment by ladyada** [comment]
hi we had a pending commit i pushed - the current code in 'master' should now retry until a valid reading comes back
https://github.com/adafruit/Adafruit_Seesaw/blob/master/Adafruit_seesaw.cpp#L276
can you try it? it should solve all any delay issues :)

**Comment by mihai-dinculescu** [comment]
That commit does indeed fix the issue.

However, the range of values is pretty large when using the retry approach.

1000 delay with retry:
image

3000 delay with no retry:
image

As a side node, I'm also a bit baffled by the fact that the value keeps going up as time passes since I've last watered the plant.

**Comment by ladyada** [comment]
huh what if you add a delay instead of continously reading?

**Comment by mihai-dinculescu** [comment]
You mean to increase the `delay` in the code below?
```
  do {
    delay(1);
    this->read(SEESAW_TOUCH_BASE, SEESAW_TOUCH_CHANNEL_OFFSET + p, buf, 2,
               1000);
    ret = ((uint16_t)buf[0] << 8) | buf[1];
  } while (ret == 65535);
```

**Comment by ladyada** [comment]
no, like, between each read of the seesaw, delay 10-20 seconds?

**Comment by mihai-dinculescu** [comment]
Oh! The readings in my example happen once every 5 minutes.

**Comment by tmm1** [comment]
@mihai-dinculescu Did you figure out why there is so much variance in values read with code from master?

**Comment by mihai-dinculescu** [comment]
> 
> 
> @mihai-dinculescu Did you figure out why there is so much variance in values read with code from master?

It can really only be because of the repeat reads. Here's another example:
blue: 3000 delay (this branch)
red: 1000 delay (master)
in both cases the value is read approx. every 5 minutes.

image

**Comment by tmm1** [comment]
If I measure how long it takes to receive the sensor value, it's only taking 6-7ms. I'm confused why the 1000 or 3000 delays are necessary.

I'm also seeing an issue on master where the retry loop gets stuck when no sensor is present and stalls everything. The return value of `endTransmission` can be used to detect if the sensor is missing and abort the loop.

**Comment by tmm1** [comment]
I see, the delay parameter is in microseconds not milliseconds..

**Comment by tmm1** [comment]
Okay, it seems to me that `touchRead` is not the correct place to add the retry loop (i.e. 87987c097e0b7fc1ea55b1b88455f3e2ee99b98d should probably be reverted). Instead, the retry logic can go inside `read`. Right now, the i2c command is sent over and over which is probably what's affecting the value.

**Comment by tmm1** [comment]
This is interesting.. I enabled `SEESAW_I2C_DEBUG` and I'm using a simple program which checks `touchRead(0)` and `getTemp()` every five seconds.

You can see the library is sending the touch i2c command twice. What's strange is the first one gets a response, but the response is `0xff,0xff`

```
I2C read $F10 : 0xFF,0xFF,
I2C read $F10 : 0x1,0x49,
I2C read $4 : 0x0,0x19,0xAA,0x96,
```

**Comment by tmm1** [comment]
@mihai-dinculescu Can you try my PR to see if it fixes your issue? #27 

Also, I'm curious what range of values you're getting from the soil sensor? In the docs it mentions 200-2000, but my sensor seems to max out at 1016.

**Comment by einarpersson** [comment]
Same here, I get 300-400 in air and 1015 in soil (independent of moist or dry).

**Pull request closed without merging**
